from __future__ import annotations

import json
import math
import re
from datetime import date
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


class PriceZoneRule(BaseModel):
    type: Literal["price_zone"] = "price_zone"
    low: float
    high: float

    @model_validator(mode="after")
    def validate_zone(self):
        if not math.isfinite(self.low) or not math.isfinite(self.high):
            raise ValueError("entry zone prices must be finite")
        if self.low <= 0 or self.high <= 0:
            raise ValueError("entry zone prices must be positive")
        if self.low > self.high:
            raise ValueError("entry low must be <= entry high")
        return self


class FixedPriceRule(BaseModel):
    type: Literal["fixed_price"] = "fixed_price"
    price: float

    @model_validator(mode="after")
    def validate_price(self):
        if not math.isfinite(self.price):
            raise ValueError("price must be finite")
        if self.price <= 0:
            raise ValueError("price must be positive")
        return self


def _validate_iso_date(value: str, field_name: str) -> None:
    text = str(value or "")
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", text):
        raise ValueError(f"{field_name} must be an ISO date")
    try:
        date.fromisoformat(text)
    except ValueError as exc:
        raise ValueError(f"{field_name} must be an ISO date") from exc


class ReanalysisTrigger(BaseModel):
    type: Literal["price_below", "price_above", "volume_spike", "moving_average_cross", "time_expired"]
    reason: str = ""
    level: float | None = None
    multiplier: float | None = None
    lookback_days: int | None = None
    ma: str | None = None
    direction: Literal["up", "down"] | None = None
    date: str | None = None

    @model_validator(mode="after")
    def validate_trigger(self):
        if self.type in {"price_below", "price_above"}:
            if self.level is None or not math.isfinite(self.level) or self.level <= 0:
                raise ValueError("price trigger level must be finite and positive")
        if self.type == "volume_spike":
            if self.multiplier is None or not math.isfinite(self.multiplier) or self.multiplier <= 1:
                raise ValueError("volume_spike multiplier must be finite and greater than 1")
            if self.lookback_days is None or self.lookback_days < 1:
                raise ValueError("volume_spike lookback_days must be positive")
        if self.type == "moving_average_cross" and (not self.ma or self.direction not in {"up", "down"}):
            raise ValueError("moving_average_cross requires ma and direction")
        if self.type == "time_expired":
            if not self.date:
                raise ValueError("time_expired requires date")
            _validate_iso_date(self.date, "time_expired date")
        return self


class StrategySpec(BaseModel):
    """Executable, deterministic strategy contract generated by agents.

    Agents may explain the strategy in prose, but execution/backtests should use
    this structure so the same rule is replayed consistently without re-calling
    the LLM.
    """

    strategy_id: str
    ticker: str
    trade_date: str
    strategy_type: Literal["price_timing_long"] = "price_timing_long"
    execution_mode: Literal["programmatic_rule_engine"] = "programmatic_rule_engine"
    entry: PriceZoneRule
    take_profit: FixedPriceRule
    stop_loss: FixedPriceRule
    currency: str = ""
    source: str = ""
    confidence: float | None = Field(default=None, ge=0, le=1)
    basis: list[str] = Field(default_factory=list)
    avoid_conditions: list[str] = Field(default_factory=list)
    valid_until: str | None = None
    reanalysis_triggers: list[ReanalysisTrigger] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_long_direction(self):
        if self.stop_loss.price >= self.entry.low:
            raise ValueError("long stop-loss must be below entry zone")
        if self.take_profit.price <= self.entry.high:
            raise ValueError("long take-profit must be above entry zone")
        if self.valid_until:
            _validate_iso_date(self.valid_until, "valid_until")
        return self

    @classmethod
    def from_price_timing_levels(
        cls,
        *,
        ticker: str,
        trade_date: str,
        levels: dict[str, Any],
        source: str = "",
        confidence: float | None = None,
        basis: list[str] | None = None,
        avoid_conditions: list[str] | None = None,
        valid_until: str | None = None,
        reanalysis_triggers: list[dict[str, Any]] | None = None,
    ) -> "StrategySpec":
        strategy_id = f"{str(ticker).upper()}-{trade_date}-price-timing"
        return cls(
            strategy_id=strategy_id,
            ticker=str(ticker).upper(),
            trade_date=str(trade_date),
            entry=PriceZoneRule(low=float(levels["entry_low"]), high=float(levels["entry_high"])),
            take_profit=FixedPriceRule(price=float(levels["take_profit"])),
            stop_loss=FixedPriceRule(price=float(levels["stop_loss"])),
            currency=str(levels.get("currency") or "").upper(),
            source=source,
            confidence=confidence,
            basis=basis or [],
            avoid_conditions=avoid_conditions or [],
            valid_until=valid_until,
            reanalysis_triggers=reanalysis_triggers or [],
        )

    def to_price_timing_levels(self) -> dict[str, Any]:
        return {
            "entry_low": round(float(self.entry.low), 4),
            "entry_high": round(float(self.entry.high), 4),
            "take_profit": round(float(self.take_profit.price), 4),
            "stop_loss": round(float(self.stop_loss.price), 4),
            "currency": self.currency,
        }


def parse_strategy_spec(raw: Any) -> StrategySpec | None:
    if isinstance(raw, StrategySpec):
        return raw
    if not isinstance(raw, dict):
        return None
    try:
        return StrategySpec.model_validate(_normalize_strategy_spec_payload(raw))
    except Exception:
        return None


def _normalize_strategy_spec_payload(raw: dict[str, Any]) -> dict[str, Any]:
    payload = dict(raw)
    for field in ("basis", "avoid_conditions"):
        value = payload.get(field)
        if isinstance(value, str):
            payload[field] = [value]

    triggers = payload.get("reanalysis_triggers")
    if isinstance(triggers, list):
        normalized_triggers: list[Any] = []
        for trigger in triggers:
            if not isinstance(trigger, dict):
                normalized_triggers.append(trigger)
                continue
            normalized = dict(trigger)
            if "reason" not in normalized and "reason_ko" in normalized:
                normalized["reason"] = normalized.pop("reason_ko")
            else:
                normalized.pop("reason_ko", None)
            if "lookback_days" not in normalized and "look_back_days" in normalized:
                normalized["lookback_days"] = normalized.pop("look_back_days")
            else:
                normalized.pop("look_back_days", None)
            trigger_type = normalized.get("type")
            if trigger_type == "moving_average_cross":
                direction = normalized.get("direction")
                if direction in {"above", "above_close"}:
                    normalized["direction"] = "up"
                elif direction in {"below", "below_close"}:
                    normalized["direction"] = "down"
                if not normalized.get("ma") or normalized.get("direction") not in {"up", "down"}:
                    continue
            else:
                normalized.pop("ma", None)
                normalized.pop("direction", None)
            if trigger_type != "volume_spike":
                normalized.pop("multiplier", None)
                normalized.pop("lookback_days", None)
            if trigger_type != "time_expired":
                normalized.pop("date", None)
            normalized_triggers.append(normalized)
        payload["reanalysis_triggers"] = normalized_triggers
    return payload


def extract_strategy_spec_from_text(text: str) -> StrategySpec | None:
    """Find a StrategySpec JSON object in an agent report, if present.

    The quant report is still human-readable markdown, so this parser is
    intentionally best-effort and validation-gated. Invalid JSON or invalid
    trading directions return None instead of creating an unsafe executable rule.
    """
    text = str(text or "")
    if "StrategySpec" not in text:
        return None

    decoder = json.JSONDecoder()
    candidates: list[Any] = []
    for fence_match in re.finditer(r"```(?:json)?\s*([\s\S]*?)```", text, flags=re.IGNORECASE):
        candidate = fence_match.group(1).strip()
        try:
            candidates.append(json.loads(candidate))
        except json.JSONDecodeError:
            continue

    for marker in re.finditer(r"StrategySpec\s*:?", text, flags=re.IGNORECASE):
        tail = text[marker.end():]
        brace_index = tail.find("{")
        if brace_index < 0:
            continue
        try:
            payload, _ = decoder.raw_decode(tail[brace_index:])
            candidates.append(payload)
        except json.JSONDecodeError:
            continue

    for payload in candidates:
        spec_payload = payload.get("StrategySpec") if isinstance(payload, dict) and isinstance(payload.get("StrategySpec"), dict) else payload
        spec = parse_strategy_spec(spec_payload)
        if spec is not None:
            return spec
    return None
